steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'PASSWORD=${_PASSWORD}'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/core'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/core'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/core']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$PROJECT_ID'
      - '--image'
      - 'gcr.io/$PROJECT_ID/core'
      - '--region'
      - 'australia-southeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/core'
