baseURL: https://etched.netlify.app/
languageCode: en-au
title: Etched
metaDataFormat: yaml
taxonomies: {}
menu:
  main:
    - name: Selected Works
      url: /selected-works/
      identifier: selected-works
      weight: 10
markup:
  goldmark:
    renderer:
      unsafe: true
