backend:
  # TODO: name: git-gateway
  name: github
  repo: florenceltf/etched
  branch: master

media_folder: /static/images/uploads/
public_folder: /images/uploads/

# https://www.netlifycms.org/docs/add-to-your-site/#editorial-workflow
publish_mode: editorial_workflow

collections:
  - label: Pages
    name: pages
    files:
      - label: Home
        name: home
        file: content/_index.md
        fields:
          - label: Gallery
            name: gallery
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
              - label: Title
                name: title
                widget: string
              - label: Layout
                name: layout
                widget: select
                multiple: false
                default: Portrait
                options:
                  - Landscape
                  - Portrait
      - label: Information
        name: info
        file: content/info/index.md
        fields:
          - label: Body
            name: body
            widget: markdown
          - label: services
            name: services
            widget: markdown
          - label: Contact
            name: contact
            widget: markdown
          - label: Collaborators
            name: collaborators
            widget: markdown

  - label: Selected Works
    name: selected-works
    folder: /content/selected-works/
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: URL
        name: slug
        widget: string
        required: false
      - label: Year
        name: year
        widget: string
      - label: Client
        name: client
        widget: string
      - label: Collaborators
        name: collaborators
        widget: string
        required: false
      - label: Category
        name: category
        widget: select
        multiple: false
        options:
          - Residential
          - Multi-Residential
          - Commercial
      - label: Description
        name: description
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: Gallery
        name: gallery
        widget: list
        fields:
          - label: Image
            name: image
            widget: image
          - label: Title
            name: title
            widget: string
          - label: Layout
            name: layout
            widget: select
            multiple: false
            default: Portrait
            options:
              - Landscape
              - Portrait
