---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Home
- type: document
  path: content/information/index.md
  label: Information
- type: document
  path: content/story/_index.md
  label: Story
  match: "**/*"
- type: document
  path: content/selected-works/_index.md
  label: Selected Works
- type: directory
  path: content/selected-works
  label: Projects
  create: documents
  match: "*"
  exclude: _index.md
  templates:
  - selected-works
- type: document
  path: data/footer.yaml
  label: Footer
upload_dir: assets/images/uploads
public_path: "/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.74.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
